name: BlossomMC
version: 1.0.0
main: net.blossom.core.BlossomMCPlugin
api-version: "1.20"
loader: net.blossom.core.BlossomPluginLoader
bootstrapper: net.blossom.core.BlossomPluginBootstrap

dependencies:
  - PacketEvents
